name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"
      
      - name: Download dependencies
        run: go mod download

      - name: Build binary
        run: go build -o webwallpaper.exe .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: ./webwallpaper.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}